### ISSUE TITLE
Solid color in gauge for each step 

### ISSUE THREAD

**Issue by alekbless** [hellocomet/vue-svg-gauge#25]
I want to use solid colors instead of gradient when adding multiple objects to gauge-color array.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Possibility to define colors like in prop 'gauge-color' but in solid not gradient.

**Describe alternatives you've considered**

**Additional context**

Grafana is doing this by calling it "thresholds". https://play.grafana.org/d/_gFwRQuZks/google-sheets-average-temperature?editPanel=4&orgId=1

I could submit a pull-request if this is an accepted feature.

**Comment by zenire** [comment]
This issue was closed without a  solution. Could you share this, please?
