### ISSUE TITLE
v1.2.0 available from the npm registry appears to have been deployed incorrectly.

### ISSUE THREAD

**Issue by spiltcoffee** [hellocomet/vue-svg-gauge#6]
**Describe the bug**
v1.2.0 available from the npm registry appears to have been deployed incorrectly.

I added `vue-svg-gauge@^1.2.0` as a dependency in my project, but it seems to be missing the changes that `1.2.0` should contain. Namely, the `transitionDuration` prop is missing from the component and `README.md`.

**To Reproduce**
1. `npm install vue-svg-gauge`
2. Attempt to use the `transitionDuration` prop.

**Expected behavior**
For the package to be the right version and the `transitionDuration` prop to be available.

**Comment by MorganeLecurieux** [comment]
Hey, sorry, not sure what happened, but version 1.2.1 is now available and working. Let me know if you experience any troubles again !
